base:
  project: Thyroid_Disorder_prediction
  random_state: 42
  target_col: Class

data_source:
  source : data_original/hypothyroid.csv

split_data:
  train_path : datas/raw/train_raw.csv
  test_path : datas/raw/test_raw.csv
  text_size: 0.3

processed: 
  train_path : datas/processed/train_processed.csv
  test_path : datas/processed/test_processed.csv

balanced_data :
  train_class: datas/balanced_data/train_balanced_class.csv
  train_label: datas/balanced_data/train_balanced_label.csv
  test_class: datas/balanced_data/test_class.csv
  test_label: datas/balanced_data/test_label.csv

metrics:
  report : reports/reports.csv